# Generated by Django 5.0.14 on 2025-05-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='artist',
            new_name='author',
        ),
    ]
